# nginx
# stable version for legacy
FROM alpine:3.14

STOPSIGNAL SIGINT

EXPOSE 8443

RUN set -ex && \
	apk update && \
	apk add --no-cache \
		musl \
		musl-utils \
		libgcc \
		libstdc++ \
		gcompat && \
    adduser -G www-data -D www-data && \
	mkdir -p /docker-entrypoint.d && \
    rm -rf /var/cache/apk/*

COPY tools/docker-entrypoint.sh /
COPY conf/configuration.sh /docker-entrypoint.d

RUN set -ex && \
	chmod +x /docker-entrypoint.d/configuration.sh /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD [ "code-server" ]

# HEALTHCHECK --interval=30s --timeout=3s \
# 	CMD wget --quiet --tries=1 --spider $CADVISOR_HEALTHCHECK_URL || exit 1
