
version : "3.8"

services:

# mariadb service
  mariadb:
    container_name: db
    build:
      context: ./requirements/mariadb
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD']
      interval: 1s
      timeout: 2s
      retries: 21
      start_period: 7s
    env_file: .env
    networks:
      - backend
    restart: always
    volumes:
      - ${INCEPTION_PATH}/db:/var/lib/mysql
      # - db_volume:/var/lib/mysql

#wordpress service
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    env_file: .env
    networks:
      - backend
      - frontend
      - cache_server
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ${INCEPTION_PATH}/wordpress:/var/www/html
      # - wordpress_volume:/var/www/html

# nginx service
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    env_file: .env
    ports:
      - "443:443"
    networks:
      - frontend
      - static_site_network
    restart: always
    depends_on:
      wordpress:
        condition: service_healthy
      site:
        condition: service_healthy
    volumes:
      - ${INCEPTION_PATH}/wordpress:/var/www/html
      # - wordpress_volume:/var/www/html







# adminer service - bonus
  adminer:
    container_name: adminer
    build:
      context:  ./requirements/bonus/adminer
    env_file: .env
    networks:
      - backend
      - frontend
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
      wordpress:
        condition: service_healthy

# static site : profile - bonus
  site:
    container_name: site
    build:
      context: ./requirements/bonus/site
    env_file: .env
    networks:
      - static_site_network
    restart: always

# redis : cache - bonus
  redis:
    container_name: redis
    build:
      context: ./requirements/bonus/redis
    env_file: .env
    networks:
      - cache_server
    restart: always
    depends_on:
      wordpress:
        condition: service_healthy

  # ftp:
  #   container_name: ftp
  #   build:
  #     context: ./requirements/bonus/ftp
  #   env_file: .env
  #   networks:
  #     - backend
  #     - frontend
  #   restart: always
  #   depends_on:
  #     nginx:
  #       condition: service_healthy






networks:
  frontend:
    driver: bridge

  static_site_network:
    driver: bridge

  backend:
    driver: bridge

  cache_server:
    driver: bridge

# volumes:
#   wordpress_volume:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ${INCEPTION_PATH}/wordpress

#   db_volume:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ${INCEPTION_PATH}/db
