
version : "3.8"

services:

# mariadb service
  mariadb:
    container_name: db
    build:
      context: requirements/mariadb
    env_file: .env
    stop_signal: SIGINT
    expose:
      - "3306"
    networks:
      - backend
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD']
      interval: 1s
      timeout: 2s
      retries: 42
    volumes:
      - ${INCEPTION_PATH}/db:/var/lib/mysql
      # - db_volume:/var/lib/mysql

#wordpress service
  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
    command: [php-fpm8, "-F"]
    env_file:
      - .env
    stop_signal: SIGINT
    expose:
      - "3306"
      - "9000"
    networks:
      - backend
      - frontend
    restart: always
    healthcheck:
      test: ['CMD', 'nc', '-z', 'localhost', '9000']
      interval: 1s
      timeout: 2s
      retries: 42
    depends_on:
      mariadb:
        condition: service_healthy
#     volumes:
#       # - ${INCEPTION_PATH}/wordpress:/var/www/html
#       - wordpress_volume:/var/www/html

# nginx service
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
    command: [nginx, '-g', 'daemon off;']
    env_file: .env
    stop_signal: SIGINT
    ports:
      - "443:443"
    expose:
      - "9000"
    hostname: localhost
    domainname: ${DOMAIN_NAME}
    networks:
      - frontend
    restart: always
    depends_on:
      wordpress:
        condition: service_healthy
    volumes:
      - ${INCEPTION_PATH}/wordpress:/var/www
      # - wordpress_volume:/var/www
      # - db_volume:/var/lib/mysql

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

# volumes:
#   wordpress_volume:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ${INCEPTION_PATH}/wordpress

#   db_volume:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ${INCEPTION_PATH}/db
