# nginx
# stable version for legacy
FROM alpine:3.14

STOPSIGNAL SIGINT

EXPOSE 2121

RUN set -ex && \
    apk add --no-cache \
        libc6-compat \
		device-mapper findutils ndctl zfs && \
    adduser -G www-data -D www-data && \
	mkdir -p /docker-entrypoint.d && \
	wget https://github.com/google/cadvisor/releases/download/v0.39.3/cadvisor && \
	chmod +x cadvisor && \
	chown www-data:www-data cadvisor && \
	mv cadvisor /usr/local/bin/ && \
    rm -rf /var/cache/apk/*

COPY tools/docker-entrypoint.sh /
COPY conf/configuration.sh /docker-entrypoint.d

RUN set -ex && \
	chmod +x /docker-entrypoint.d/configuration.sh /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD [ "cadvisor", "-logtostderr" ]

ENV CADVISOR_HEALTHCHECK_URL=http://localhost:8080/healthz

HEALTHCHECK --interval=30s --timeout=3s \
	CMD wget --quiet --tries=1 --spider $CADVISOR_HEALTHCHECK_URL || exit 1
