# nginx
# stable version for legacy
FROM alpine:3.14

STOPSIGNAL SIGINT

EXPOSE 2121

RUN set -ex && \
    apk add --no-cache \
        libc6-compat && \
    addgroup www-data && \
    adduser -G www-data -D www-data && \
	mkdir -p /docker-entrypoint.d && \
	wget https://github.com/google/cadvisor/releases/download/v0.39.3/cadvisor && \
	chmod +x cadvisor && \
	chown www-data:www-data cadvisor && \
	mv cadvisor /usr/local/bin/ && \
    rm -rf /var/cache/apk/*

COPY tools/docker-entrypoint.sh /
COPY conf/configuration.sh /docker-entrypoint.d

RUN set -ex && \
	chmod +x /docker-entrypoint.d/configuration.sh /docker-entrypoint.sh
    # chown -R redis:redis /docker-entrypoint.d

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD [ "cadvisor", "-logtostderr" ]

# HEALTHCHECK --interval=1s --timeout=2s --start-period=3s --retries=30 \
            # CMD [ "redis-cli", "ping" ]
