# nginx
# stable version for legacy
FROM alpine:3.14

STOPSIGNAL SIGINT

EXPOSE 6379

RUN set -ex && \
    # apk update && \
    apk add --no-cache \
        redis && \
	mkdir -p /docker-entrypoint.d && \
    rm -rf /var/cache/apk/*

COPY tools/docker-entrypoint.sh /
COPY conf/configuration.sh /docker-entrypoint.d

RUN set -ex && \
	chmod +x /docker-entrypoint.d/configuration.sh /docker-entrypoint.sh && \
    chown -R redis:redis /docker-entrypoint.d

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD [ "redis-server" ]

HEALTHCHECK --interval=1s --timeout=2s --start-period=3s --retries=30 \
            CMD [ "redis-cli", "ping" ]
