# nginx
# stable version for legacy
FROM alpine:3.14

STOPSIGNAL SIGINT

EXPOSE 6379

HEALTHCHECK --interval=1s --timeout=2s --start-period=3s --retries=30 \
            CMD [ "redis-cli", "ping" ]

RUN apk add --no-cache \
    redis && \
	mkdir -p /docker-entrypoint.d && \
    rm -rf /var/cache/apk/*

COPY tools/docker-entrypoint.sh /
COPY conf/configuration.sh /docker-entrypoint.d

RUN set -e && \
	chmod +x /docker-entrypoint.d/configuration.sh /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD [ "redis-server" ]



