# nginx
FROM alpine:3.14

STOPSIGNAL SIGINT

EXPOSE 4242

HEALTHCHECK --interval=1s --timeout=2s --start-period=1s --retries=30 \
            CMD [ "nc", "-z", "localhost", "4242" ]

RUN set -ex && \
    apk add --no-cache \
        nginx && \
    mkdir -p /docker-entrypoint.d && \
    rm -rf /var/cache/apk/*

COPY tools/docker-entrypoint.sh /
COPY conf/configuration.sh /docker-entrypoint.d
COPY conf/profile_source/ /profile/profile_source
COPY conf/profile.html /profile

RUN set -ex && \
    chmod +x /docker-entrypoint.d/configuration.sh /docker-entrypoint.sh /profile/profile.html

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["nginx", "-g", "daemon off;"]
